name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Reposityory çekiliyor
      uses: actions/checkout@v3

    - name: Node.js kuruluyor
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Paketler yükleniyor
      run: npm install

    - name: Test çalýþtýrýlýyor
      run: npm test
